### PR TITLE
src: don't round-trip through thread pool

### PR DESCRIPTION
**Pull request by bnoordhuis**
Before this commit, a dummy uv_work_t request was used to force the
event loop to cycle.  It works but it means an unnecessary round-trip
through the thread pool, which is a fairly constrained resource to start
with.

Rewrite it to use a uv_idle_t handle paired with a queue of batons that
get dispatched in the idle callback.  A future optimization is to hand
off the pending batons in a single call to JS land rather than making
a callback per baton.

Fix a minor resource leak due to a missing HandleScope while we're here.

(+2 code cleanup commits.)

Suggested reviewer: @AndrewMartens?

### CODE REVIEW

**Comment by sam-github** [comment]
LGTM

/to @AndrewMartens Seems an API compatible improvement. This will make 0.10 collection better, so can it be merged into your staging?

And FYI, its not a replacement for what @bnoordhuis is doing on the node side, which will likely be API similar.

/to @bnoordhuis If `.onGC( becomes`.on('gc',` in node-core, we can change here, too.

**Comment by bnoordhuis** [comment]
As discussed with Sam on IRC, I can change the first commit from named namespaces to anonymous namespaces.  That should avoid naming conflicts with with other hypothetical nodefly modules that use nodefly::internal as a namespace.

**Comment by AndrewMartens** [comment]
Looks good to me!

**Comment by bnoordhuis** [comment]
Thanks for the review.  Landed with the aforementioned fix-up.

**Pull request closed without merging**
